In [1]:
import numpy as np
import pandas as pd

In [2]:
header = ['user_id', 'age', 'sex', 'occupation','zipcode']
users_data = pd.read_table('C:\\Users\\Sirivamsi\\Documents\\Big Data\\Project\\Project Files\\ml-100k\\u.user', sep='|', names=header)

In [3]:
users_data.head()

user_id  age sex  occupation zipcode
0        1   24   M  technician   85711
1        2   53   F       other   94043
2        3   23   M      writer   32067
3        4   24   M  technician   43537
4        5   33   F       other   15213

In [4]:
header = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_table('C:\\Users\\Sirivamsi\\Documents\\Big Data\\Project\\Project Files\\ml-100k\\u.data', sep='\t', names=header)

In [5]:
n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print ("Number of users = " + str(n_users) + " | Number of movies = " + str(n_items))

Number of users = 943 | Number of movies = 1682


In [6]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.25)
print (train_data)

       user_id  item_id  rating  timestamp
99840      921       25       3  879379736
2805       276       85       3  874791871
50050      545       96       5  879899233
82515      717      312       5  884642133
9127       303      164       4  879466830
6217       240      300       3  885775563
86729      733      471       3  879535814
17924      303      765       3  879485608
55052      829      278       1  881712488
72743      851      264       2  890343477
26372      343       89       3  876406006
91898      320      597       3  884748774
26890      171      258       4  891034801
93698       28      603       3  881957090
68483      271      215       4  885849300
21297      139      740       2  879538254
74156      748      132       3  879454998
5983       303      202       5  879468149
15027      395      632       5  883764845
99792      897      523       5  879991186
85215      864      470       4  888890052
85534      931      137       3  891036552
66004      

In [7]:
print (test_data)

       user_id  item_id  rating  timestamp
74248      909      289       3  891920763
79490      795      472       3  880559543
91188      181      544       1  878962919
85924      414       11       5  884999347
58277      747      693       5  888732899
1331       138      517       4  879024279
20995      145     1288       4  888398197
36383      141      284       5  884585071
36583      389     1114       2  880614050
90425      940      100       3  885921471
85815      560       58       3  879975485
59248      711      568       3  879995238
69409      878       50       4  880865562
33077      403      288       4  879785822
29996        8      174       5  879362183
79955      932      180       4  891251014
57657      504      294       2  887912722
4340        13      820       4  882398743
12740      234      242       4  891033261
9180        10      385       4  877886783
68579      235      524       5  889655204
62364      743      303       5  881277357
6205       

In [8]:
output = []
output1 = []
output2 = []
output3 = []
output4 = []
output5 = []
output6 = []
for row in train_data.itertuples():
    for row2 in users_data.itertuples():
        if row[1] == row2[1] and row2[2]>3 and row2[2]<18:
            output.append(row[1])
        elif row[1] == row2[1] and row2[2]>17 and row2[2]<36 and row2[3]=='M':
            output1.append(row[1])
        elif row[1] == row2[1] and row2[2]>17 and row2[2]<36 and row2[3]=='F':
            output2.append(row[1])
        elif row[1] == row2[1] and row2[2]>35 and row2[2]<56 and row2[3]=='M':
            output3.append(row[1])   
        elif row[1] == row2[1] and row2[2]>35 and row2[2]<56 and row2[3]=='F':
            output4.append(row[1]) 
        elif row[1] == row2[1] and row2[2]>55 and row2[2]<95 and row2[3]=='M':
            output5.append(row[1]) 
        elif row[1] == row2[1] and row2[2]>55 and row2[2]<95 and row2[3]=='F':
            output6.append(row[1]) 

In [9]:
output7 = []
output7=np.unique(output)
print (output7)
num_of_rows1=np.count_nonzero(output7)
group_one_matrix = np.zeros((num_of_rows1,n_items+1))
k=0
u=1
for i in np.nditer(output7):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
              group_one_matrix[k-1, j[2]-1] = j[3]
              group_one_matrix[k-1,n_items] = 1
        else:
            u=u+1
group_one_matrix = np.concatenate((output7[:, np.newaxis], group_one_matrix), axis=1)  
print (group_one_matrix)
output8 = []
output8=np.unique(output1)
print (output8)
num_of_rows2=np.count_nonzero(output8)
group_two_matrix = np.zeros((num_of_rows2,n_items+1))
k=0
u=1
for i in np.nditer(output8):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
              group_two_matrix[k-1, j[2]-1] = j[3]
              group_two_matrix[k-1,n_items] = 2
        else:
            u=u+1
group_two_matrix = np.concatenate((output8[:, np.newaxis], group_two_matrix), axis=1)  
output9 = []
output9=np.unique(output2)
print (output9)
num_of_rows3=np.count_nonzero(output9)
group_three_matrix = np.zeros((num_of_rows3,n_items+1))
k=0
u=1
for i in np.nditer(output9):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
              group_three_matrix[k-1, j[2]-1] = j[3]
              group_three_matrix[k-1,n_items] = 3
        else:
            u=u+1
group_three_matrix = np.concatenate((output9[:, np.newaxis], group_three_matrix), axis=1)  
output10 = []
output10=np.unique(output3)
print (output10)
num_of_rows4=np.count_nonzero(output10)
group_four_matrix = np.zeros((num_of_rows4,n_items+1))
k=0
u=1
for i in np.nditer(output10):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
              group_four_matrix[k-1, j[2]-1] = j[3]
              group_four_matrix[k-1,n_items] = 4
        else:
            u=u+1
group_four_matrix = np.concatenate((output10[:, np.newaxis], group_four_matrix), axis=1)  
output11 = []
output11=np.unique(output4)
print (output11)
num_of_rows5=np.count_nonzero(output11)
group_five_matrix = np.zeros((num_of_rows5,n_items+1))
k=0
u=1
for i in np.nditer(output11):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
              group_five_matrix[k-1, j[2]-1] = j[3]
              group_five_matrix[k-1,n_items] = 5
        else:
            u=u+1
group_five_matrix = np.concatenate((output11[:, np.newaxis], group_five_matrix), axis=1)  
output12 = []
output12=np.unique(output5)
print (output12)
num_of_rows6=np.count_nonzero(output12)
group_six_matrix = np.zeros((num_of_rows6,n_items+1))
k=0
u=1
for i in np.nditer(output12):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
            group_six_matrix[k-1, j[2]-1] = j[3]
            group_six_matrix[k-1,n_items] = 6
        else:
            u=u+1
group_six_matrix = np.concatenate((output12[:, np.newaxis], group_six_matrix), axis=1)  
output13 = []
output13=np.unique(output6)
print (output13)
num_of_rows7=np.count_nonzero(output13)
group_seven_matrix = np.zeros((num_of_rows7,n_items+1))
k=0
u=1
for i in np.nditer(output13):
    k=k+1
    for j in train_data.itertuples():
        if i==j[1]:
              group_seven_matrix[k-1, j[2]-1] = j[3]
              group_seven_matrix[k-1,n_items] = 7
        else:
            u=u+1
group_seven_matrix = np.concatenate((output13[:, np.newaxis], group_seven_matrix), axis=1)  

[ 30  57  67 101 142 179 206 257 281 289 341 367 375 397 434 451 461 471
 550 580 582 609 618 619 621 628 646 674 700 761 813 849 863 880 887 904]
[[ 30.   0.   3. ...   0.   0.   1.]
 [ 57.   5.   0. ...   0.   0.   1.]
 [ 67.   3.   0. ...   0.   0.   1.]
 ...
 [880.   0.   3. ...   0.   0.   1.]
 [887.   5.   0. ...   0.   0.   1.]
 [904.   0.   0. ...   0.   0.   1.]]
[  1   3   4   9  16  17  21  22  28  31  33  37  41  42  44  45  50  51
  53  54  56  58  63  64  66  68  69  70  73  75  76  77  78  81  84  86
  92  94  95  99 103 104 105 109 110 112 114 115 117 118 119 124 125 127
 130 132 134 135 139 145 148 153 154 156 160 162 176 177 178 181 183 187
 189 190 191 193 199 201 213 215 216 217 219 220 221 222 226 242 243 244
 245 246 247 248 249 250 251 255 259 261 265 267 268 272 276 279 282 283
 285 286 287 288 291 293 294 295 299 301 303 305 307 311 315 317 320 322
 323 327 331 332 334 336 339 346 347 350 353 355 357 359 361 363 365 368
 369 377 378 380 381 387 388 391 393 394 

In [124]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity1 = np.zeros((num_of_rows1,n_items))
user_similarity2 = np.zeros((num_of_rows2,n_items))
user_similarity3 = np.zeros((num_of_rows3,n_items))
user_similarity4 = np.zeros((num_of_rows4,n_items))
user_similarity5 = np.zeros((num_of_rows5,n_items))
user_similarity6 = np.zeros((num_of_rows6,n_items))
user_similarity7 = np.zeros((num_of_rows7,n_items))

user_similarity1 = pairwise_distances(group_one_matrix[:,1:n_items-1], metric='cosine')
user_similarity2 = pairwise_distances(group_two_matrix[:,1:n_items-1], metric='cosine')
user_similarity3 = pairwise_distances(group_three_matrix[:,1:n_items-1], metric='cosine')
user_similarity4 = pairwise_distances(group_four_matrix[:,1:n_items-1], metric='cosine')
user_similarity5 = pairwise_distances(group_five_matrix[:,1:n_items-1], metric='cosine')
user_similarity6 = pairwise_distances(group_six_matrix[:,1:n_items-1], metric='cosine')
user_similarity7 = pairwise_distances(group_seven_matrix[:,1:n_items-1], metric='cosine')

user_similarity1 = np.concatenate((output7[:, np.newaxis], user_similarity1), axis=1)
user_similarity2 = np.concatenate((output8[:, np.newaxis], user_similarity2), axis=1) 
user_similarity3 = np.concatenate((output9[:, np.newaxis], user_similarity3), axis=1) 
user_similarity4 = np.concatenate((output10[:, np.newaxis], user_similarity4), axis=1) 
user_similarity5 = np.concatenate((output11[:, np.newaxis], user_similarity5), axis=1) 
user_similarity6 = np.concatenate((output12[:, np.newaxis], user_similarity6), axis=1) 
user_similarity7 = np.concatenate((output13[:, np.newaxis], user_similarity7), axis=1)




In [155]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity1 = np.zeros((num_of_rows1,n_items))
user_similarity2 = np.zeros((num_of_rows2,n_items))
user_similarity3 = np.zeros((num_of_rows3,n_items))
user_similarity4 = np.zeros((num_of_rows4,n_items))
user_similarity5 = np.zeros((num_of_rows5,n_items))
user_similarity6 = np.zeros((num_of_rows6,n_items))
user_similarity7 = np.zeros((num_of_rows7,n_items))

user_similarity1 = adjusted_cosine_similarity_user(group_one_matrix[:,1:n_items-1])
user_similarity2 = adjusted_cosine_similarity_user(group_two_matrix[:,1:n_items-1])
user_similarity3 = adjusted_cosine_similarity_user(group_three_matrix[:,1:n_items-1])
user_similarity4 = adjusted_cosine_similarity_user(group_four_matrix[:,1:n_items-1])
user_similarity5 = adjusted_cosine_similarity_user(group_five_matrix[:,1:n_items-1])
user_similarity6 = adjusted_cosine_similarity_user(group_six_matrix[:,1:n_items-1])
user_similarity7 = adjusted_cosine_similarity_user(group_seven_matrix[:,1:n_items-1])


user_similarity1 = np.concatenate((output7[:, np.newaxis], user_similarity1), axis=1)
user_similarity2 = np.concatenate((output8[:, np.newaxis], user_similarity2), axis=1) 
user_similarity3 = np.concatenate((output9[:, np.newaxis], user_similarity3), axis=1) 
user_similarity4 = np.concatenate((output10[:, np.newaxis], user_similarity4), axis=1) 
user_similarity5 = np.concatenate((output11[:, np.newaxis], user_similarity5), axis=1) 
user_similarity6 = np.concatenate((output12[:, np.newaxis], user_similarity6), axis=1) 
user_similarity7 = np.concatenate((output13[:, np.newaxis], user_similarity7), axis=1)

In [154]:
def adjusted_cosine_similarity_user(matrix):
   matrix_mean = matrix.mean(axis=1)
   user_mean_subtracted = matrix - matrix_mean[:, None]
   similaritymatrix = pairwise_distances(user_mean_subtracted, metric='cosine')
   return similaritymatrix

In [98]:
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
user_similarity1 = np.zeros((num_of_rows1,n_items))
user_similarity2 = np.zeros((num_of_rows2,n_items))
user_similarity3 = np.zeros((num_of_rows3,n_items))
user_similarity4 = np.zeros((num_of_rows4,n_items))
user_similarity5 = np.zeros((num_of_rows5,n_items))
user_similarity6 = np.zeros((num_of_rows6,n_items))
user_similarity7 = np.zeros((num_of_rows7,n_items))

user_similarity1 = squareform(pdist(group_one_matrix[:,1:n_items-1], 'correlation'))
user_similarity2 = squareform(pdist(group_two_matrix[:,1:n_items-1], 'correlation'))
user_similarity3 = squareform(pdist(group_three_matrix[:,1:n_items-1], 'correlation'))
user_similarity4 = squareform(pdist(group_four_matrix[:,1:n_items-1], 'correlation'))
user_similarity5 = squareform(pdist(group_five_matrix[:,1:n_items-1], 'correlation'))
user_similarity6 = squareform(pdist(group_six_matrix[:,1:n_items-1], 'correlation'))
user_similarity7 = squareform(pdist(group_seven_matrix[:,1:n_items-1], 'correlation'))

print(user_similarity1)
user_similarity1 = np.concatenate((output7[:, np.newaxis], user_similarity1), axis=1)
user_similarity2 = np.concatenate((output8[:, np.newaxis], user_similarity2), axis=1) 
user_similarity3 = np.concatenate((output9[:, np.newaxis], user_similarity3), axis=1) 
user_similarity4 = np.concatenate((output10[:, np.newaxis], user_similarity4), axis=1) 
user_similarity5 = np.concatenate((output11[:, np.newaxis], user_similarity5), axis=1) 
user_similarity6 = np.concatenate((output12[:, np.newaxis], user_similarity6), axis=1) 
user_similarity7 = np.concatenate((output13[:, np.newaxis], user_similarity7), axis=1)

[[0.         0.90741883 0.96295497 ... 0.9008756  0.88517524 0.92758762]
 [0.90741883 0.         0.76812206 ... 0.80114909 0.79759163 0.9463249 ]
 [0.96295497 0.76812206 0.         ... 0.88394748 0.83303656 0.96570556]
 ...
 [0.9008756  0.80114909 0.88394748 ... 0.         0.789212   0.89455921]
 [0.88517524 0.79759163 0.83303656 ... 0.789212   0.         0.94827759]
 [0.92758762 0.9463249  0.96570556 ... 0.89455921 0.94827759 0.        ]]


In [11]:
test_data_matrix = np.zeros((n_users, n_items))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
    
    

In [13]:
testoutput = []
testoutput1 = []
testoutput2 = []
testoutput3 = []
testoutput4 = []
testoutput5 = []
testoutput6 = []
for row in test_data.itertuples():
    for row2 in users_data.itertuples():
        if row[1] == row2[1] and row2[2]>3 and row2[2]<18:
            testoutput= np.append(testoutput,row[1])
        elif row[1] == row2[1] and row2[2]>17 and row2[2]<36 and row2[3]=='M':
            testoutput1 = np.append(testoutput1,row[1])
        elif row[1] == row2[1] and row2[2]>17 and row2[2]<36 and row2[3]=='F':
            testoutput2 = np.append(testoutput2,row[1])
        elif row[1] == row2[1] and row2[2]>35 and row2[2]<56 and row2[3]=='M':
            testoutput3 = np.append(testoutput3,row[1])   
        elif row[1] == row2[1] and row2[2]>35 and row2[2]<56 and row2[3]=='F':
            testoutput4 = np.append(testoutput4,row[1])
        elif row[1] == row2[1] and row2[2]>55 and row2[2]<95 and row2[3]=='M':
            testoutput5 = np.append(testoutput5,row[1]) 
        elif row[1] == row2[1] and row2[2]>55 and row2[2]<95 and row2[3]=='F':
            testoutput6 = np.append(testoutput6,row[1])

In [14]:
testoutput=np.unique(testoutput)
testoutput1=np.unique(testoutput1)
testoutput2=np.unique(testoutput2)
testoutput3=np.unique(testoutput3)
testoutput4=np.unique(testoutput4)
testoutput5=np.unique(testoutput5)
testoutput6=np.unique(testoutput6)


In [15]:
train_data_matrix = np.zeros((n_users, n_items))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]
print (train_data_matrix)



[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


In [102]:
from sklearn.metrics import mean_absolute_error
from math import sqrt
def calcpredandmae(testgroup,user_similarity_matrix, noofrows, prediction, originalvalues, k):
  for p in np.nditer(testgroup):
     v=0   
     for q in user_similarity_matrix[:,0:1]:
        v=v+1
        if p == q:
          similardata = user_similarity_matrix[v-1,1:noofrows+1] 
          similarindexvalues = np.argsort(user_similarity_matrix[v-1,1:noofrows+1])
          user_item_matrix = np.zeros((0,n_items))
          totalcount = len(similarindexvalues)
          temp = 1-k
          getnumofusers = np.rint(totalcount*temp).astype(int)
          for z in similarindexvalues[getnumofusers:totalcount+1]:
            similar_users = (user_similarity_matrix[z,0:1]).astype(int)
            user_item_matrix = np.append(user_item_matrix,(train_data_matrix[similar_users-1]),axis=0)  
          item_similarity = pairwise_distances(user_item_matrix.T, metric='cosine')
          item_id_to_calc = []
          for r in test_data.itertuples():               
                if r[1] == p:
                   similaritemindexvalues = np.argsort(item_similarity[r[2]-1]) 
                   numerator=0
                   denominator=0
                   predictedvalue=0                   
                   for x in similaritemindexvalues:
                       rawrating = train_data_matrix[r[1]-1,x-1].astype(int)
                       if rawrating!=0:
                          simofrating = item_similarity[r[2]-1,x-1].astype(int)
                          numerator = numerator + (rawrating*simofrating)
                          denominator= denominator + item_similarity[r[2]-1,x-1]
                   predictedvalue = numerator/denominator         
                   prediction = np.append(prediction,predictedvalue)
                   originalvalues = np.append(originalvalues,r[3])                                                              
  return originalvalues, prediction

In [138]:
def adjusted_cosine_similarity(matrix):
   matrix_mean = matrix.mean(axis=1)
   user_mean_subtracted = matrix - matrix_mean[:, None]
   similaritymatrix = pairwise_distances(user_mean_subtracted.T, metric='cosine')
   return similaritymatrix
   

In [161]:
from sklearn.metrics import mean_absolute_error
from scipy.spatial.distance import squareform
from sklearn.metrics.pairwise import pairwise_distances
from math import sqrt
def calcpredandmae1(testgroup,user_similarity_matrix, noofrows, prediction, originalvalues, k):
  for p in np.nditer(testgroup):
     v=0   
     for q in user_similarity_matrix[:,0:1]:
        v=v+1
        if p == q:
          similardata = user_similarity_matrix[v-1,1:noofrows+1] 
          similarindexvalues = np.argsort(user_similarity_matrix[v-1,1:noofrows+1])
          user_item_matrix = np.zeros((0,n_items))
          totalcount = len(similarindexvalues)
          temp = 1-k
          getnumofusers = np.rint(totalcount*temp).astype(int)
          for z in similarindexvalues[getnumofusers:totalcount+1]:
            similar_users = (user_similarity_matrix[z,0:1]).astype(int)
            user_item_matrix = np.append(user_item_matrix,(train_data_matrix[similar_users-1]),axis=0)  
          item_similarity = adjusted_cosine_similarity(user_item_matrix)
          item_id_to_calc = []
          for r in test_data.itertuples():               
                if r[1] == p:
                   similaritemindexvalues = np.argsort(item_similarity[r[2]-1]) 
                   numerator=0
                   denominator=0
                   predictedvalue=0                   
                   for x in similaritemindexvalues:
                       rawrating = train_data_matrix[r[1]-1,x-1].astype(int)
                       if rawrating!=0:
                          simofrating = item_similarity[r[2]-1,x-1].astype(int)
                          numerator = numerator + (rawrating*simofrating)
                          denominator= denominator + item_similarity[r[2]-1,x-1]
                   if denominator == 0:
                      predictedvalue = 0
                   else:
                      predictedvalue = numerator/denominator     
                   prediction = np.append(prediction,predictedvalue)
                   originalvalues = np.append(originalvalues,r[3])                                                              
  return originalvalues, prediction

In [114]:
similardata = []
datatobepredicted = []
originalvaluesintestdata = []
k = 1/8
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput,user_similarity1,num_of_rows1,datatobepredicted,originalvaluesintestdata,k)
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput1,user_similarity2,num_of_rows2,datatobepredicted,originalvaluesintestdata,k)
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput2,user_similarity3,num_of_rows3,datatobepredicted,originalvaluesintestdata,k)
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput3,user_similarity4,num_of_rows4,datatobepredicted,originalvaluesintestdata,k)
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput4,user_similarity5,num_of_rows5,datatobepredicted,originalvaluesintestdata,k)
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput5,user_similarity6,num_of_rows6,datatobepredicted,originalvaluesintestdata,k)
originalvaluesintestdata, datatobepredicted = calcpredandmae(testoutput6,user_similarity7,num_of_rows7,datatobepredicted,originalvaluesintestdata,k)
print (originalvaluesintestdata.shape)
print (datatobepredicted.shape)
print (mean_absolute_error(originalvaluesintestdata,datatobepredicted))
mae = mean_absolute_error(originalvaluesintestdata,datatobepredicted)
results = np.append(mae,k)
print(results)

KeyboardInterrupt: 

In [166]:
results = []
groupsize = []

In [170]:
similardata = []
datatobepredicted1 = []
originalvaluesintestdata1 = []

k = 1/2
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput,user_similarity1,num_of_rows1,datatobepredicted1,originalvaluesintestdata1,k)
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput1,user_similarity2,num_of_rows2,datatobepredicted1,originalvaluesintestdata1,k)
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput2,user_similarity3,num_of_rows3,datatobepredicted1,originalvaluesintestdata1,k)
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput3,user_similarity4,num_of_rows4,datatobepredicted1,originalvaluesintestdata1,k)
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput4,user_similarity5,num_of_rows5,datatobepredicted1,originalvaluesintestdata1,k)
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput5,user_similarity6,num_of_rows6,datatobepredicted1,originalvaluesintestdata1,k)
originalvaluesintestdata1, datatobepredicted1 = calcpredandmae1(testoutput6,user_similarity7,num_of_rows7,datatobepredicted1,originalvaluesintestdata1,k)
print (originalvaluesintestdata1.shape)
print (datatobepredicted1.shape)
mae = mean_absolute_error(originalvaluesintestdata1,datatobepredicted1)

groupsize = np.append(groupsize,k)
results = np.append(results,mae)

print (results)
print (groupsize)

(25000,)
(25000,)
[1.67593072 1.67593072]
[0.125 0.25  0.5   0.5  ]
